import type { Metadata } from 'next'
import Link from 'next/link'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body>
				<main className='relative flex h-screen'>
					{children}
					<div className='absolute bottom-3 left-0 right-0 flex justify-center text-2xl'>
						This game owned by Laughing with Nextjs -
						<Link
							href='#'
							className='text-yellow-400 underline ml-1'
						>
							view here
						</Link>
					</div>
				</main>
			</body>
		</html>
	)
}
